apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
        group: iot
        tier: frontend
    spec:
      volumes:
        - name: nodered-pv-storage
          hostPath:
            path: /home/ubuntu/data
            type: Directory
      containers:
      - name: nodered
        image: registry.gitlab.com/mc-b/iot-kafka/node-red:v1.3.5
        ports:
        - containerPort: 1880
          hostPort: 1880
        volumeMounts:
         - name: nodered-pv-storage
           mountPath: /data
           
