apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
        group: iot
        tier: frontend
    spec:
      containers:
      - name: nodered
        image: registry.gitlab.com/mc-b/iot-kafka/node-red-kafka
        ports:
        - containerPort: 1880
          hostPort: 1880
          
